### ISSUE TITLE
Server Error. /relint/revelrylabs/pairr/1055

### ISSUE THREAD

**Issue by RevelryMark** [revelrylabs/lintron#169]
received link ( ### ) from Travis, but click thru results in: 
"We're sorry, but something went wrong.

If you are the application owner check the logs for more information."

info from logs
###

**Comment by RevelryMark** [comment]
same behavior https://lintron.io/relint/revelrylabs/townpros/859

**Comment by RevelryMark** [comment]
Both the above GitHub user RevelryMark
Safari Version 12.0.2
macOS 10.14.2

**Comment by prehnRA** [comment]
Should be fixed now.
